#-------------------------------------------------
#
# Project created by QtCreator 2014-11-08T23:20:24
#
#-------------------------------------------------

QT       += core gui opengl

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TARGET = editor
TEMPLATE = app

exists($$PWD/machine_specific.txt) {
    include($$PWD/machine_specific.txt)
}

SOURCES += main.cpp\
    main_window.cpp \
    ../src/xd/vendor/glm/detail/glm.cpp \
    ../src/vendor/base64.cpp \
    ../src/vendor/lutf8lib.cpp \
    ../src/vendor/platform_folders.cpp \
    ../src/vendor/physfs.cpp \
    ../src/camera.cpp \
    ../src/canvas/base_canvas.cpp \
    ../src/canvas/base_image_canvas.cpp \
    ../src/canvas/canvas_renderer.cpp \
    ../src/canvas/canvas_updater.cpp \
    ../src/canvas/image_canvas.cpp \
    ../src/canvas/sprite_canvas.cpp \
    ../src/canvas/text_canvas.cpp \
    ../src/audio_player.cpp \
    ../src/clock.cpp \
    ../src/commands/command.cpp \
    ../src/commands/command_result.cpp \
    ../src/commands/timed_command.cpp \
    ../src/commands/fade_music_command.cpp \
    ../src/commands/move_camera_command.cpp \
    ../src/commands/move_canvas_command.cpp \
    ../src/commands/move_object_command.cpp \
    ../src/commands/move_object_to_command.cpp \
    ../src/commands/shake_screen_command.cpp \
    ../src/commands/show_pose_command.cpp \
    ../src/commands/show_text_command.cpp \
    ../src/commands/text_options.cpp \
    ../src/commands/tint_command.cpp \
    ../src/commands/update_image_command.cpp \
    ../src/commands/update_color_command.cpp \
    ../src/commands/update_opacity_command.cpp \
    ../src/commands/update_layer_velocity_command.cpp \
    ../src/commands/wait_command.cpp \
    ../src/commands/zoom_command.cpp \
    ../src/configurations.cpp \
    ../src/custom_shaders.cpp \
    ../src/interfaces/editable.cpp \
    ../src/interfaces/sprite_holder.cpp \
    ../src/game.cpp \
    ../src/map/layers/image_layer.cpp \
    ../src/map/layers/image_layer_renderer.cpp \
    ../src/map/layers/image_layer_updater.cpp \
    ../src/key_binder.cpp \
    ../src/map/layers/layer.cpp \
    ../src/map/layers/layer_renderer.cpp \
    ../src/log.cpp \
    ../src/map/map.cpp \
    ../src/map/map_object.cpp \
    ../src/map/collision_check_options.cpp \
    ../src/map/layers/object_layer.cpp \
    ../src/map/layers/object_layer_renderer.cpp \
    ../src/map/layers/object_layer_updater.cpp \
    ../src/pathfinder.cpp \
    ../src/player_controller.cpp \
    ../src/save_file.cpp \
    ../src/scripting/bindings/canvas_bindings.cpp \
    ../src/scripting/bindings/environment_bindings.cpp \
    ../src/scripting/bindings/game_bindings.cpp \
    ../src/scripting/bindings/audio_bindings.cpp \
    ../src/scripting/bindings/camera_bindings.cpp \
    ../src/scripting/bindings/file_bindings.cpp \
    ../src/scripting/bindings/layer_bindings.cpp \
    ../src/scripting/bindings/map_bindings.cpp \
    ../src/scripting/bindings/map_object_bindings.cpp \
    ../src/scripting/bindings/math_bindings.cpp \
    ../src/scripting/bindings/text_bindings.cpp \
    ../src/scripting/bindings/utility_bindings.cpp \
    ../src/scripting/lua_object.cpp \
    ../src/scripting/scripting_interface.cpp \
    ../src/decorators/shake_decorator.cpp \
    ../src/decorators/typewriter_decorator.cpp \
    ../src/environments/default_environment.cpp \
    ../src/environments/steam_environment.cpp \
    ../src/sprite.cpp \
    ../src/sprite_data.cpp \
    ../src/text_parser.cpp \
    ../src/map/layers/tile_layer.cpp \
    ../src/map/layers/tile_layer_renderer.cpp \
    ../src/map/tileset.cpp \
    ../src/map/tmx_properties.cpp \
    ../src/utility/math.cpp \
    ../src/utility/file.cpp \
    ../src/utility/string.cpp \
    ../src/utility/color.cpp \
    ../src/utility/xml.cpp \
    ../src/filesystem/boost_filesystem.cpp \
    ../src/filesystem/disk_filesystem.cpp \
    ../src/filesystem/physfs_filesystem.cpp \
    ../src/filesystem/standard_filesystem.cpp \
    ../src/filesystem/user_data_folder.cpp \
    ../src/xd/audio/detail/fmod_audio_handle.cpp \
    ../src/xd/audio/detail/fmod_sound_handle.cpp \
    ../src/xd/audio/audio.cpp \
    ../src/xd/audio/music.cpp \
    ../src/xd/audio/sound.cpp \
    ../src/xd/graphics/font.cpp \
    ../src/xd/graphics/framebuffer.cpp \
    ../src/xd/graphics/image.cpp \
    ../src/xd/graphics/shader_program.cpp \
    ../src/xd/graphics/shaders.cpp \
    ../src/xd/graphics/sprite_batch.cpp \
    ../src/xd/graphics/stock_text_formatter.cpp \
    ../src/xd/graphics/text_formatter.cpp \
    ../src/xd/graphics/text_renderer.cpp \
    ../src/xd/graphics/texture.cpp \
    ../src/xd/lua/scheduler.cpp \
    ../src/xd/lua/virtual_machine.cpp \
    ../src/xd/system/input.cpp \
    ../src/xd/system/window.cpp \
    map_view.cpp \
    mappers/image_layer_mapper.cpp \
    mappers/layer_mapper.cpp \
    mappers/map_mapper.cpp \
    mappers/map_object_mapper.cpp \
    mappers/object_layer_mapper.cpp \
    property_editor.cpp \
    qtpropertybrowser/src/qtbuttonpropertybrowser.cpp \
    qtpropertybrowser/src/qteditorfactory.cpp \
    qtpropertybrowser/src/qtgroupboxpropertybrowser.cpp \
    qtpropertybrowser/src/qtpropertybrowser.cpp \
    qtpropertybrowser/src/qtpropertybrowserutils.cpp \
    qtpropertybrowser/src/qtpropertymanager.cpp \
    qtpropertybrowser/src/qttreepropertybrowser.cpp \
    qtpropertybrowser/src/qtvariantproperty.cpp

HEADERS  += main_window.hpp \
    ../src/vendor/base64.hpp \
    ../src/vendor/lutf8lib.hpp \
    ../src/vendor/platform_folders.hpp \
    ../src/vendor/rapidxml.hpp \
    ../src/vendor/rapidxml_print.hpp \
    ../src/vendor/unidata.h \
    ../src/vendor/utf8conv.h \
    ../src/vendor/physfs.hpp \
    ../src/camera.hpp \
    ../src/canvas/base_canvas.hpp \
    ../src/canvas/base_image_canvas.hpp \
    ../src/canvas/canvas_renderer.hpp \
    ../src/canvas/canvas_updater.hpp \
    ../src/canvas/image_canvas.hpp \
    ../src/canvas/sprite_canvas.hpp \
    ../src/canvas/text_canvas.hpp \
    ../src/audio_player.hpp \
    ../src/clock.hpp \
    ../src/map/collision_check_options.hpp \
    ../src/map/collision_check_types.hpp \
    ../src/map/collision_record.hpp \
    ../src/commands/command.hpp \
    ../src/commands/command_result.hpp \
    ../src/commands/timed_command.hpp \
    ../src/commands/fade_music_command.hpp \
    ../src/commands/move_camera_command.hpp \
    ../src/commands/move_canvas_command.hpp \
    ../src/commands/move_object_command.hpp \
    ../src/commands/move_object_to_command.hpp \
    ../src/commands/shake_screen_command.hpp \
    ../src/commands/show_pose_command.hpp \
    ../src/commands/show_text_command.hpp \
    ../src/commands/text_options.hpp \
    ../src/commands/tint_command.hpp \
    ../src/commands/update_image_command.hpp \
    ../src/commands/update_color_command.hpp \
    ../src/commands/update_opacity_command.hpp \
    ../src/commands/update_layer_velocity_command.hpp \
    ../src/commands/wait_command.hpp \
    ../src/commands/zoom_command.hpp \
    ../src/configurations.hpp \
    ../src/custom_shaders.hpp \
    ../src/direction.hpp \
    ../src/exceptions.hpp \
    ../src/game.hpp \
    ../src/interfaces/editable.hpp \
    ../src/interfaces/opacity_holder.hpp \
    ../src/interfaces/sprite_holder.hpp \
    ../src/map/layers/image_layer.hpp \
    ../src/map/layers/image_layer_renderer.hpp \
    ../src/map/layers/image_layer_updater.hpp \
    ../src/key_binder.hpp \
    ../src/map/layers/layer.hpp \
    ../src/map/layers/layer_renderer.hpp \
    ../src/map/layers/layer_types.hpp \
    ../src/map/layers/layer_updater.hpp \
    ../src/log.hpp \
    ../src/map/map.hpp \
    ../src/map/map_object.hpp \
    ../src/map/layers/object_layer.hpp \
    ../src/map/layers/object_layer_renderer.hpp \
    ../src/map/layers/object_layer_updater.hpp \
    ../src/pathfinder.hpp \
    ../src/player_controller.hpp \
    ../src/vendor/rapidxml.hpp \
    ../src/vendor/rapidxml_print.hpp \
    ../src/save_file.hpp \
    ../src/scripting/script_bindings.hpp \
    ../src/scripting/lua_object.hpp \
    ../src/scripting/scripting_interface.hpp \
    ../src/decorators/shake_decorator.hpp \
    ../src/decorators/typewriter_decorator.hpp \
    ../src/environments/default_environment.hpp \
    ../src/environments/environment.hpp \
    ../src/environments/steam_environment.hpp \
    ../src/sprite.hpp \
    ../src/sprite_data.hpp \
    ../src/tests/game_fixture.hpp \
    ../src/text_parser.hpp \
    ../src/map/layers/tile_layer.hpp \
    ../src/map/layers/tile_layer_renderer.hpp \
    ../src/map/tileset.hpp \
    ../src/map/tmx_properties.hpp \
    ../src/utility/color.hpp \
    ../src/utility/direction.hpp \
    ../src/utility/file.hpp \
    ../src/utility/math.hpp \
    ../src/utility/string.hpp \
    ../src/utility/xml.hpp \
    ../src/filesystem/boost_filesystem.hpp \
    ../src/filesystem/disk_filesystem.hpp \
    ../src/filesystem/physfs_filesystem.hpp \
    ../src/filesystem/path_info.hpp \
    ../src/filesystem/readable_filesystem.hpp \
    ../src/filesystem/standard_filesystem.hpp \
    ../src/filesystem/user_data_folder.hpp \
    ../src/filesystem/writable_filesystem.hpp \
    ../src/xd/asset_manager.hpp \
    ../src/xd/audio.hpp \
    ../src/xd/audio/audio.hpp \
    ../src/xd/audio/detail/audio_handle.hpp \
    ../src/xd/audio/detail/sound_handle.hpp \
    ../src/xd/audio/detail/fmod_audio_handle.hpp \
    ../src/xd/audio/detail/fmod_sound_handle.hpp \
    ../src/xd/audio/channel_group_type.hpp \
    ../src/xd/audio/exceptions.hpp \
    ../src/xd/audio/music.hpp \
    ../src/xd/audio/sound.hpp \
    ../src/xd/detail/entity.hpp \
    ../src/xd/detail/identity.hpp \
    ../src/xd/detail/noop_deleter.hpp \
    ../src/xd/entity.hpp \
    ../src/xd/event_bus.hpp \
    ../src/xd/exception.hpp \
    ../src/xd/glm.hpp \
    ../src/xd/graphics/detail/font.hpp \
    ../src/xd/graphics/detail/image.hpp \
    ../src/xd/graphics/detail/sprite_batch.hpp \
    ../src/xd/graphics/detail/text_formatter.hpp \
    ../src/xd/graphics/detail/vertex_traits.hpp \
    ../src/xd/graphics/exceptions.hpp \
    ../src/xd/graphics/font.hpp \
    ../src/xd/graphics/font_style.hpp \
    ../src/xd/graphics/framebuffer.hpp \
    ../src/xd/graphics/image.hpp \
    ../src/xd/graphics/matrix_stack.hpp \
    ../src/xd/graphics/shader_program.hpp \
    ../src/xd/graphics/shaders.hpp \
    ../src/xd/graphics/sprite_batch.hpp \
    ../src/xd/graphics/stock_text_formatter.hpp \
    ../src/xd/graphics/text_formatter.hpp \
    ../src/xd/graphics/text_renderer.hpp \
    ../src/xd/graphics/texture.hpp \
    ../src/xd/graphics/transform_geometry.hpp \
    ../src/xd/graphics/types.hpp \
    ../src/xd/graphics/utility.hpp \
    ../src/xd/graphics/vertex_batch.hpp \
    ../src/xd/graphics/vertex_traits.hpp \
    ../src/xd/lua/exceptions.hpp \
    ../src/xd/lua/scheduler.hpp \
    ../src/xd/lua/scheduler_task.hpp \
    ../src/xd/lua/virtual_machine.hpp \
    ../src/xd/system/exceptions.hpp \
    ../src/xd/system/input.hpp \
    ../src/xd/system/window.hpp \
    ../src/xd/system/window_options.hpp \
    map_view.hpp \
    mappers/image_layer_mapper.hpp \
    mappers/layer_mapper.hpp \
    mappers/map_mapper.hpp \
    mappers/map_object_mapper.hpp \
    mappers/object_layer_mapper.hpp \
    property_editor.hpp \
    qtpropertybrowser/src/qtbuttonpropertybrowser.h \
    qtpropertybrowser/src/qteditorfactory.h \
    qtpropertybrowser/src/qtgroupboxpropertybrowser.h \
    qtpropertybrowser/src/qtpropertybrowser.h \
    qtpropertybrowser/src/qtpropertybrowserutils_p.h \
    qtpropertybrowser/src/qtpropertymanager.h \
    qtpropertybrowser/src/qttreepropertybrowser.h \
    qtpropertybrowser/src/qtvariantproperty.h

FORMS    += main_window.ui

DISTFILES += \
    ../src/xd/vendor/glm/CMakeLists.txt

QMAKE_CXXFLAGS += /std:c++17 /bigobj
