#-------------------------------------------------
#
# Project created by QtCreator 2014-11-08T23:20:24
#
#-------------------------------------------------

QT       += core gui opengl

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TARGET = editor
TEMPLATE = app

exists($$PWD/machine_specific.txt) {
    include($$PWD/machine_specific.txt)
}

SOURCES += main.cpp\
        main_window.cpp \
    map_view.cpp \
    ../src/base64.cpp \
    ../src/camera.cpp \
    ../src/canvas.cpp \
    ../src/canvas_renderer.cpp \
    ../src/canvas_updater.cpp \
    ../src/clock.cpp \
    ../src/collision_record.cpp \
    ../src/command_result.cpp \
    ../src/configurations.cpp \
    ../src/custom_shaders.cpp \
    ../src/editable.cpp \
    ../src/game.cpp \
    ../src/image_layer.cpp \
    ../src/image_layer_renderer.cpp \
    ../src/image_layer_updater.cpp \
    ../src/layer.cpp \
    ../src/log.cpp \
    ../src/map.cpp \
    ../src/map_object.cpp \
    ../src/object_layer.cpp \
    ../src/object_layer_renderer.cpp \
    ../src/object_layer_updater.cpp \
    ../src/pathfinder.cpp \
    ../src/player_controller.cpp \
    ../src/scripting_interface.cpp \
    ../src/sprite.cpp \
    ../src/sprite_data.cpp \
    ../src/tile_layer.cpp \
    ../src/tile_layer_renderer.cpp \
    ../src/tileset.cpp \
    ../src/utility.cpp \
    ../src/save_file.cpp \
    qtpropertybrowser/src/qtbuttonpropertybrowser.cpp \
    qtpropertybrowser/src/qteditorfactory.cpp \
    qtpropertybrowser/src/qtgroupboxpropertybrowser.cpp \
    qtpropertybrowser/src/qtpropertybrowser.cpp \
    qtpropertybrowser/src/qtpropertybrowserutils.cpp \
    qtpropertybrowser/src/qtpropertymanager.cpp \
    qtpropertybrowser/src/qttreepropertybrowser.cpp \
    qtpropertybrowser/src/qtvariantproperty.cpp \
    property_editor.cpp \
    mappers/map_object_mapper.cpp \
    ../src/sprite_holder.cpp \
    mappers/image_layer_mapper.cpp \
    mappers/layer_mapper.cpp \
    mappers/object_layer_mapper.cpp \
    mappers/map_mapper.cpp \
    ../src/layer_renderer.cpp \
    ../src/command.cpp \
    ../src/commands/fade_music_command.cpp \
    ../src/commands/move_camera_command.cpp \
    ../src/commands/move_object_command.cpp \
    ../src/commands/move_object_to_command.cpp \
    ../src/commands/shake_screen_command.cpp \
    ../src/commands/show_pose_command.cpp \
    ../src/commands/show_text_command.cpp \
    ../src/commands/tint_screen_command.cpp \
    ../src/commands/update_canvas_command.cpp \
    ../src/commands/update_layer_command.cpp \
    ../src/commands/wait_command.cpp \
    ../src/text_parser.cpp \
    ../src/commands/zoom_command.cpp \
    ../src/shake_decorator.cpp \
    ../include/xd/vendor/glm/detail/glm.cpp \
    ../src/commands/fade_music_command.cpp \
    ../src/commands/move_camera_command.cpp \
    ../src/commands/move_object_command.cpp \
    ../src/commands/move_object_to_command.cpp \
    ../src/commands/shake_screen_command.cpp \
    ../src/commands/show_pose_command.cpp \
    ../src/commands/show_text_command.cpp \
    ../src/commands/tint_screen_command.cpp \
    ../src/commands/update_canvas_command.cpp \
    ../src/commands/update_layer_command.cpp \
    ../src/commands/wait_command.cpp \
    ../src/commands/zoom_command.cpp \
    ../src/xd/audio/audio.cpp \
    ../src/xd/audio/music.cpp \
    ../src/xd/audio/sound.cpp \
    ../src/xd/graphics/font.cpp \
    ../src/xd/graphics/framebuffer.cpp \
    ../src/xd/graphics/image.cpp \
    ../src/xd/graphics/shader_program.cpp \
    ../src/xd/graphics/shaders.cpp \
    ../src/xd/graphics/simple_text_renderer.cpp \
    ../src/xd/graphics/sprite_batch.cpp \
    ../src/xd/graphics/stock_text_formatter.cpp \
    ../src/xd/graphics/text_formatter.cpp \
    ../src/xd/graphics/text_renderer.cpp \
    ../src/xd/graphics/texture.cpp \
    ../src/xd/lua/scheduler.cpp \
    ../src/xd/lua/virtual_machine.cpp \
    ../src/xd/system/input.cpp \
    ../src/xd/system/window.cpp \
    ../src/base64.cpp \
    ../src/camera.cpp \
    ../src/canvas.cpp \
    ../src/canvas_renderer.cpp \
    ../src/canvas_updater.cpp \
    ../src/clock.cpp \
    ../src/collision_record.cpp \
    ../src/command.cpp \
    ../src/command_result.cpp \
    ../src/configurations.cpp \
    ../src/custom_shaders.cpp \
    ../src/Editable.cpp \
    ../src/game.cpp \
    ../src/image_layer.cpp \
    ../src/image_layer_renderer.cpp \
    ../src/image_layer_updater.cpp \
    ../src/layer.cpp \
    ../src/layer_renderer.cpp \
    ../src/log.cpp \
    ../src/main.cpp \
    ../src/map.cpp \
    ../src/map_object.cpp \
    ../src/object_layer.cpp \
    ../src/object_layer_renderer.cpp \
    ../src/object_layer_updater.cpp \
    ../src/pathfinder.cpp \
    ../src/player_controller.cpp \
    ../src/save_file.cpp \
    ../src/scripting_interface.cpp \
    ../src/shake_decorator.cpp \
    ../src/sprite.cpp \
    ../src/sprite_data.cpp \
    ../src/sprite_holder.cpp \
    ../src/text_parser.cpp \
    ../src/tile_layer.cpp \
    ../src/tile_layer_renderer.cpp \
    ../src/tileset.cpp \
    ../src/utility.cpp

HEADERS  += main_window.hpp \
    map_view.hpp \
    ../include/base64.hpp \
    ../include/camera.hpp \
    ../include/canvas.hpp \
    ../include/canvas_renderer.hpp \
    ../include/canvas_updater.hpp \
    ../include/clock.hpp \
    ../include/collision_check_types.hpp \
    ../include/collision_record.hpp \
    ../include/command.hpp \
    ../include/command_result.hpp \
    ../include/commands.hpp \
    ../include/common.hpp \
    ../include/configurations.hpp \
    ../include/custom_shaders.hpp \
    ../include/direction.hpp \
    ../include/direction_utilities.hpp \
    ../include/exceptions.hpp \
    ../include/game.hpp \
    ../include/image_layer.hpp \
    ../include/image_layer_renderer.hpp \
    ../include/image_layer_updater.hpp \
    ../include/layer.hpp \
    ../include/layer_renderer.hpp \
    ../include/layer_types.hpp \
    ../include/layer_updater.hpp \
    ../include/log.hpp \
    ../include/map.hpp \
    ../include/map_object.hpp \
    ../include/object_layer.hpp \
    ../include/object_layer_renderer.hpp \
    ../include/object_layer_updater.hpp \
    ../include/pathfinder.hpp \
    ../include/player_controller.hpp \
    ../include/rapidxml.hpp \
    ../include/scripting_interface.hpp \
    ../include/sprite.hpp \
    ../include/sprite_data.hpp \
    ../include/sprite_holder.hpp \
    ../include/tile_layer.hpp \
    ../include/tile_layer_renderer.hpp \
    ../include/tileset.hpp \
    ../include/utility.hpp \
    ../include/save_file.hpp \
    qtpropertybrowser/src/qtbuttonpropertybrowser.h \
    qtpropertybrowser/src/qteditorfactory.h \
    qtpropertybrowser/src/qtgroupboxpropertybrowser.h \
    qtpropertybrowser/src/qtpropertybrowser.h \
    qtpropertybrowser/src/qtpropertybrowserutils_p.h \
    qtpropertybrowser/src/qtpropertymanager.h \
    qtpropertybrowser/src/qttreepropertybrowser.h \
    qtpropertybrowser/src/qtvariantproperty.h \
    ui_main_window.h \
    property_editor.hpp \
    ../include/editable.hpp \
    mappers/map_object_mapper.hpp \
    mappers/image_layer_mapper.hpp \
    mappers/layer_mapper.hpp \
    mappers/object_layer_mapper.hpp \
    mappers/map_mapper.hpp \
    ../include/rapidxml_print.hpp \
    ../include/commands/fade_music_command.hpp \
    ../include/commands/move_camera_command.hpp \
    ../include/commands/move_object_command.hpp \
    ../include/commands/move_object_to_command.hpp \
    ../include/commands/shake_screen_command.hpp \
    ../include/commands/show_pose_command.hpp \
    ../include/commands/show_text_command.hpp \
    ../include/commands/tint_screen_command.hpp \
    ../include/commands/update_canvas_command.hpp \
    ../include/commands/update_layer_command.hpp \
    ../include/commands/wait_command.hpp \
    ../include/text_parser.hpp \
    ../include/commands/zoom_command.hpp \
    ../include/commands/fade_music_command.hpp \
    ../include/commands/move_camera_command.hpp \
    ../include/commands/move_object_command.hpp \
    ../include/commands/move_object_to_command.hpp \
    ../include/commands/shake_screen_command.hpp \
    ../include/commands/show_pose_command.hpp \
    ../include/commands/show_text_command.hpp \
    ../include/commands/tint_screen_command.hpp \
    ../include/commands/update_canvas_command.hpp \
    ../include/commands/update_layer_command.hpp \
    ../include/commands/wait_command.hpp \
    ../include/commands/zoom_command.hpp \
    ../include/tests/game_fixture.hpp \
    ../include/xd/audio/detail/audio_handle.hpp \
    ../include/xd/audio/audio.hpp \
    ../include/xd/audio/exceptions.hpp \
    ../include/xd/audio/music.hpp \
    ../include/xd/audio/sound.hpp \
    ../include/xd/detail/entity.hpp \
    ../include/xd/detail/identity.hpp \
    ../include/xd/detail/iterate_asset_manager.hpp \
    ../include/xd/detail/iterate_create.hpp \
    ../include/xd/detail/iterate_entity_constructor.hpp \
    ../include/xd/detail/iterate_factory_create.hpp \
    ../include/xd/detail/noop_deleter.hpp \
    ../include/xd/graphics/detail/font.hpp \
    ../include/xd/graphics/detail/image.hpp \
    ../include/xd/graphics/detail/iterate_render.hpp \
    ../include/xd/graphics/detail/sprite_batch.hpp \
    ../include/xd/graphics/detail/text_formatter.hpp \
    ../include/xd/graphics/detail/vertex_traits.hpp \
    ../include/xd/graphics/exceptions.hpp \
    ../include/xd/graphics/font.hpp \
    ../include/xd/graphics/font_style.hpp \
    ../include/xd/graphics/framebuffer.hpp \
    ../include/xd/graphics/image.hpp \
    ../include/xd/graphics/matrix_stack.hpp \
    ../include/xd/graphics/shader_program.hpp \
    ../include/xd/graphics/shaders.hpp \
    ../include/xd/graphics/simple_text_renderer.hpp \
    ../include/xd/graphics/sprite_batch.hpp \
    ../include/xd/graphics/stock_text_formatter.hpp \
    ../include/xd/graphics/text_formatter.hpp \
    ../include/xd/graphics/text_renderer.hpp \
    ../include/xd/graphics/texture.hpp \
    ../include/xd/graphics/transform_geometry.hpp \
    ../include/xd/graphics/types.hpp \
    ../include/xd/graphics/utility.hpp \
    ../include/xd/graphics/vertex_batch.hpp \
    ../include/xd/graphics/vertex_traits.hpp \
    ../include/xd/lua/detail/iterate_function_call.hpp \
    ../include/xd/lua/detail/iterate_scheduler_yield.hpp \
    ../include/xd/lua/detail/scheduler.hpp \
    ../include/xd/lua/detail/scheduler_task.hpp \
    ../include/xd/lua/config.hpp \
    ../include/xd/lua/exceptions.hpp \
    ../include/xd/lua/function.hpp \
    ../include/xd/lua/scheduler.hpp \
    ../include/xd/lua/scheduler_task.hpp \
    ../include/xd/lua/types.hpp \
    ../include/xd/lua/virtual_machine.hpp \
    ../include/xd/system/exceptions.hpp \
    ../include/xd/system/input.hpp \
    ../include/xd/system/window.hpp \
    ../include/xd/system/window_options.hpp \
    ../include/xd/vendor/glew/glew.h \
    ../include/xd/vendor/glew/glxew.h \
    ../include/xd/vendor/glew/wglew.h \
    ../include/xd/vendor/glm/detail/_features.hpp \
    ../include/xd/vendor/glm/detail/_fixes.hpp \
    ../include/xd/vendor/glm/detail/_noise.hpp \
    ../include/xd/vendor/glm/detail/_swizzle.hpp \
    ../include/xd/vendor/glm/detail/_swizzle_func.hpp \
    ../include/xd/vendor/glm/detail/_vectorize.hpp \
    ../include/xd/vendor/glm/detail/func_common.hpp \
    ../include/xd/vendor/glm/detail/func_common.inl \
    ../include/xd/vendor/glm/detail/func_exponential.hpp \
    ../include/xd/vendor/glm/detail/func_exponential.inl \
    ../include/xd/vendor/glm/detail/func_geometric.hpp \
    ../include/xd/vendor/glm/detail/func_geometric.inl \
    ../include/xd/vendor/glm/detail/func_integer.hpp \
    ../include/xd/vendor/glm/detail/func_integer.inl \
    ../include/xd/vendor/glm/detail/func_matrix.hpp \
    ../include/xd/vendor/glm/detail/func_matrix.inl \
    ../include/xd/vendor/glm/detail/func_packing.hpp \
    ../include/xd/vendor/glm/detail/func_packing.inl \
    ../include/xd/vendor/glm/detail/func_trigonometric.hpp \
    ../include/xd/vendor/glm/detail/func_trigonometric.inl \
    ../include/xd/vendor/glm/detail/func_vector_relational.hpp \
    ../include/xd/vendor/glm/detail/func_vector_relational.inl \
    ../include/xd/vendor/glm/detail/intrinsic_common.hpp \
    ../include/xd/vendor/glm/detail/intrinsic_common.inl \
    ../include/xd/vendor/glm/detail/intrinsic_exponential.hpp \
    ../include/xd/vendor/glm/detail/intrinsic_exponential.inl \
    ../include/xd/vendor/glm/detail/intrinsic_geometric.hpp \
    ../include/xd/vendor/glm/detail/intrinsic_geometric.inl \
    ../include/xd/vendor/glm/detail/intrinsic_integer.hpp \
    ../include/xd/vendor/glm/detail/intrinsic_integer.inl \
    ../include/xd/vendor/glm/detail/intrinsic_matrix.hpp \
    ../include/xd/vendor/glm/detail/intrinsic_matrix.inl \
    ../include/xd/vendor/glm/detail/intrinsic_trigonometric.hpp \
    ../include/xd/vendor/glm/detail/intrinsic_trigonometric.inl \
    ../include/xd/vendor/glm/detail/intrinsic_vector_relational.hpp \
    ../include/xd/vendor/glm/detail/intrinsic_vector_relational.inl \
    ../include/xd/vendor/glm/detail/precision.hpp \
    ../include/xd/vendor/glm/detail/setup.hpp \
    ../include/xd/vendor/glm/detail/type_float.hpp \
    ../include/xd/vendor/glm/detail/type_gentype.hpp \
    ../include/xd/vendor/glm/detail/type_gentype.inl \
    ../include/xd/vendor/glm/detail/type_half.hpp \
    ../include/xd/vendor/glm/detail/type_half.inl \
    ../include/xd/vendor/glm/detail/type_int.hpp \
    ../include/xd/vendor/glm/detail/type_mat.hpp \
    ../include/xd/vendor/glm/detail/type_mat.inl \
    ../include/xd/vendor/glm/detail/type_mat2x2.hpp \
    ../include/xd/vendor/glm/detail/type_mat2x2.inl \
    ../include/xd/vendor/glm/detail/type_mat2x3.hpp \
    ../include/xd/vendor/glm/detail/type_mat2x3.inl \
    ../include/xd/vendor/glm/detail/type_mat2x4.hpp \
    ../include/xd/vendor/glm/detail/type_mat2x4.inl \
    ../include/xd/vendor/glm/detail/type_mat3x2.hpp \
    ../include/xd/vendor/glm/detail/type_mat3x2.inl \
    ../include/xd/vendor/glm/detail/type_mat3x3.hpp \
    ../include/xd/vendor/glm/detail/type_mat3x3.inl \
    ../include/xd/vendor/glm/detail/type_mat3x4.hpp \
    ../include/xd/vendor/glm/detail/type_mat3x4.inl \
    ../include/xd/vendor/glm/detail/type_mat4x2.hpp \
    ../include/xd/vendor/glm/detail/type_mat4x2.inl \
    ../include/xd/vendor/glm/detail/type_mat4x3.hpp \
    ../include/xd/vendor/glm/detail/type_mat4x3.inl \
    ../include/xd/vendor/glm/detail/type_mat4x4.hpp \
    ../include/xd/vendor/glm/detail/type_mat4x4.inl \
    ../include/xd/vendor/glm/detail/type_vec.hpp \
    ../include/xd/vendor/glm/detail/type_vec.inl \
    ../include/xd/vendor/glm/detail/type_vec1.hpp \
    ../include/xd/vendor/glm/detail/type_vec1.inl \
    ../include/xd/vendor/glm/detail/type_vec2.hpp \
    ../include/xd/vendor/glm/detail/type_vec2.inl \
    ../include/xd/vendor/glm/detail/type_vec3.hpp \
    ../include/xd/vendor/glm/detail/type_vec3.inl \
    ../include/xd/vendor/glm/detail/type_vec4.hpp \
    ../include/xd/vendor/glm/detail/type_vec4.inl \
    ../include/xd/vendor/glm/detail/type_vec4_avx.inl \
    ../include/xd/vendor/glm/detail/type_vec4_avx2.inl \
    ../include/xd/vendor/glm/detail/type_vec4_sse2.inl \
    ../include/xd/vendor/glm/gtc/bitfield.hpp \
    ../include/xd/vendor/glm/gtc/bitfield.inl \
    ../include/xd/vendor/glm/gtc/color_space.hpp \
    ../include/xd/vendor/glm/gtc/color_space.inl \
    ../include/xd/vendor/glm/gtc/constants.hpp \
    ../include/xd/vendor/glm/gtc/constants.inl \
    ../include/xd/vendor/glm/gtc/epsilon.hpp \
    ../include/xd/vendor/glm/gtc/epsilon.inl \
    ../include/xd/vendor/glm/gtc/integer.hpp \
    ../include/xd/vendor/glm/gtc/integer.inl \
    ../include/xd/vendor/glm/gtc/matrix_access.hpp \
    ../include/xd/vendor/glm/gtc/matrix_access.inl \
    ../include/xd/vendor/glm/gtc/matrix_integer.hpp \
    ../include/xd/vendor/glm/gtc/matrix_inverse.hpp \
    ../include/xd/vendor/glm/gtc/matrix_inverse.inl \
    ../include/xd/vendor/glm/gtc/matrix_transform.hpp \
    ../include/xd/vendor/glm/gtc/matrix_transform.inl \
    ../include/xd/vendor/glm/gtc/noise.hpp \
    ../include/xd/vendor/glm/gtc/noise.inl \
    ../include/xd/vendor/glm/gtc/packing.hpp \
    ../include/xd/vendor/glm/gtc/packing.inl \
    ../include/xd/vendor/glm/gtc/quaternion.hpp \
    ../include/xd/vendor/glm/gtc/quaternion.inl \
    ../include/xd/vendor/glm/gtc/random.hpp \
    ../include/xd/vendor/glm/gtc/random.inl \
    ../include/xd/vendor/glm/gtc/reciprocal.hpp \
    ../include/xd/vendor/glm/gtc/reciprocal.inl \
    ../include/xd/vendor/glm/gtc/round.hpp \
    ../include/xd/vendor/glm/gtc/round.inl \
    ../include/xd/vendor/glm/gtc/type_precision.hpp \
    ../include/xd/vendor/glm/gtc/type_precision.inl \
    ../include/xd/vendor/glm/gtc/type_ptr.hpp \
    ../include/xd/vendor/glm/gtc/type_ptr.inl \
    ../include/xd/vendor/glm/gtc/ulp.hpp \
    ../include/xd/vendor/glm/gtc/ulp.inl \
    ../include/xd/vendor/glm/gtc/vec1.hpp \
    ../include/xd/vendor/glm/gtc/vec1.inl \
    ../include/xd/vendor/glm/gtx/associated_min_max.hpp \
    ../include/xd/vendor/glm/gtx/associated_min_max.inl \
    ../include/xd/vendor/glm/gtx/bit.hpp \
    ../include/xd/vendor/glm/gtx/bit.inl \
    ../include/xd/vendor/glm/gtx/closest_point.hpp \
    ../include/xd/vendor/glm/gtx/closest_point.inl \
    ../include/xd/vendor/glm/gtx/color_space.hpp \
    ../include/xd/vendor/glm/gtx/color_space.inl \
    ../include/xd/vendor/glm/gtx/color_space_YCoCg.hpp \
    ../include/xd/vendor/glm/gtx/color_space_YCoCg.inl \
    ../include/xd/vendor/glm/gtx/common.hpp \
    ../include/xd/vendor/glm/gtx/common.inl \
    ../include/xd/vendor/glm/gtx/compatibility.hpp \
    ../include/xd/vendor/glm/gtx/compatibility.inl \
    ../include/xd/vendor/glm/gtx/component_wise.hpp \
    ../include/xd/vendor/glm/gtx/component_wise.inl \
    ../include/xd/vendor/glm/gtx/dual_quaternion.hpp \
    ../include/xd/vendor/glm/gtx/dual_quaternion.inl \
    ../include/xd/vendor/glm/gtx/euler_angles.hpp \
    ../include/xd/vendor/glm/gtx/euler_angles.inl \
    ../include/xd/vendor/glm/gtx/extend.hpp \
    ../include/xd/vendor/glm/gtx/extend.inl \
    ../include/xd/vendor/glm/gtx/extented_min_max.hpp \
    ../include/xd/vendor/glm/gtx/extented_min_max.inl \
    ../include/xd/vendor/glm/gtx/fast_exponential.hpp \
    ../include/xd/vendor/glm/gtx/fast_exponential.inl \
    ../include/xd/vendor/glm/gtx/fast_square_root.hpp \
    ../include/xd/vendor/glm/gtx/fast_square_root.inl \
    ../include/xd/vendor/glm/gtx/fast_trigonometry.hpp \
    ../include/xd/vendor/glm/gtx/fast_trigonometry.inl \
    ../include/xd/vendor/glm/gtx/gradient_paint.hpp \
    ../include/xd/vendor/glm/gtx/gradient_paint.inl \
    ../include/xd/vendor/glm/gtx/handed_coordinate_space.hpp \
    ../include/xd/vendor/glm/gtx/handed_coordinate_space.inl \
    ../include/xd/vendor/glm/gtx/hash.hpp \
    ../include/xd/vendor/glm/gtx/hash.inl \
    ../include/xd/vendor/glm/gtx/integer.hpp \
    ../include/xd/vendor/glm/gtx/integer.inl \
    ../include/xd/vendor/glm/gtx/intersect.hpp \
    ../include/xd/vendor/glm/gtx/intersect.inl \
    ../include/xd/vendor/glm/gtx/io.hpp \
    ../include/xd/vendor/glm/gtx/io.inl \
    ../include/xd/vendor/glm/gtx/log_base.hpp \
    ../include/xd/vendor/glm/gtx/log_base.inl \
    ../include/xd/vendor/glm/gtx/matrix_cross_product.hpp \
    ../include/xd/vendor/glm/gtx/matrix_cross_product.inl \
    ../include/xd/vendor/glm/gtx/matrix_decompose.hpp \
    ../include/xd/vendor/glm/gtx/matrix_decompose.inl \
    ../include/xd/vendor/glm/gtx/matrix_interpolation.hpp \
    ../include/xd/vendor/glm/gtx/matrix_interpolation.inl \
    ../include/xd/vendor/glm/gtx/matrix_major_storage.hpp \
    ../include/xd/vendor/glm/gtx/matrix_major_storage.inl \
    ../include/xd/vendor/glm/gtx/matrix_operation.hpp \
    ../include/xd/vendor/glm/gtx/matrix_operation.inl \
    ../include/xd/vendor/glm/gtx/matrix_query.hpp \
    ../include/xd/vendor/glm/gtx/matrix_query.inl \
    ../include/xd/vendor/glm/gtx/matrix_transform_2d.hpp \
    ../include/xd/vendor/glm/gtx/matrix_transform_2d.inl \
    ../include/xd/vendor/glm/gtx/mixed_product.hpp \
    ../include/xd/vendor/glm/gtx/mixed_product.inl \
    ../include/xd/vendor/glm/gtx/norm.hpp \
    ../include/xd/vendor/glm/gtx/norm.inl \
    ../include/xd/vendor/glm/gtx/normal.hpp \
    ../include/xd/vendor/glm/gtx/normal.inl \
    ../include/xd/vendor/glm/gtx/normalize_dot.hpp \
    ../include/xd/vendor/glm/gtx/normalize_dot.inl \
    ../include/xd/vendor/glm/gtx/number_precision.hpp \
    ../include/xd/vendor/glm/gtx/number_precision.inl \
    ../include/xd/vendor/glm/gtx/optimum_pow.hpp \
    ../include/xd/vendor/glm/gtx/optimum_pow.inl \
    ../include/xd/vendor/glm/gtx/orthonormalize.hpp \
    ../include/xd/vendor/glm/gtx/orthonormalize.inl \
    ../include/xd/vendor/glm/gtx/perpendicular.hpp \
    ../include/xd/vendor/glm/gtx/perpendicular.inl \
    ../include/xd/vendor/glm/gtx/polar_coordinates.hpp \
    ../include/xd/vendor/glm/gtx/polar_coordinates.inl \
    ../include/xd/vendor/glm/gtx/projection.hpp \
    ../include/xd/vendor/glm/gtx/projection.inl \
    ../include/xd/vendor/glm/gtx/quaternion.hpp \
    ../include/xd/vendor/glm/gtx/quaternion.inl \
    ../include/xd/vendor/glm/gtx/range.hpp \
    ../include/xd/vendor/glm/gtx/raw_data.hpp \
    ../include/xd/vendor/glm/gtx/raw_data.inl \
    ../include/xd/vendor/glm/gtx/rotate_normalized_axis.hpp \
    ../include/xd/vendor/glm/gtx/rotate_normalized_axis.inl \
    ../include/xd/vendor/glm/gtx/rotate_vector.hpp \
    ../include/xd/vendor/glm/gtx/rotate_vector.inl \
    ../include/xd/vendor/glm/gtx/scalar_multiplication.hpp \
    ../include/xd/vendor/glm/gtx/scalar_relational.hpp \
    ../include/xd/vendor/glm/gtx/scalar_relational.inl \
    ../include/xd/vendor/glm/gtx/simd_mat4.hpp \
    ../include/xd/vendor/glm/gtx/simd_mat4.inl \
    ../include/xd/vendor/glm/gtx/simd_quat.hpp \
    ../include/xd/vendor/glm/gtx/simd_quat.inl \
    ../include/xd/vendor/glm/gtx/simd_vec4.hpp \
    ../include/xd/vendor/glm/gtx/simd_vec4.inl \
    ../include/xd/vendor/glm/gtx/spline.hpp \
    ../include/xd/vendor/glm/gtx/spline.inl \
    ../include/xd/vendor/glm/gtx/std_based_type.hpp \
    ../include/xd/vendor/glm/gtx/std_based_type.inl \
    ../include/xd/vendor/glm/gtx/string_cast.hpp \
    ../include/xd/vendor/glm/gtx/string_cast.inl \
    ../include/xd/vendor/glm/gtx/transform.hpp \
    ../include/xd/vendor/glm/gtx/transform.inl \
    ../include/xd/vendor/glm/gtx/transform2.hpp \
    ../include/xd/vendor/glm/gtx/transform2.inl \
    ../include/xd/vendor/glm/gtx/type_aligned.hpp \
    ../include/xd/vendor/glm/gtx/type_aligned.inl \
    ../include/xd/vendor/glm/gtx/vector_angle.hpp \
    ../include/xd/vendor/glm/gtx/vector_angle.inl \
    ../include/xd/vendor/glm/gtx/vector_query.hpp \
    ../include/xd/vendor/glm/gtx/vector_query.inl \
    ../include/xd/vendor/glm/gtx/wrap.hpp \
    ../include/xd/vendor/glm/gtx/wrap.inl \
    ../include/xd/vendor/glm/common.hpp \
    ../include/xd/vendor/glm/exponential.hpp \
    ../include/xd/vendor/glm/ext.hpp \
    ../include/xd/vendor/glm/fwd.hpp \
    ../include/xd/vendor/glm/geometric.hpp \
    ../include/xd/vendor/glm/glm.hpp \
    ../include/xd/vendor/glm/integer.hpp \
    ../include/xd/vendor/glm/mat2x2.hpp \
    ../include/xd/vendor/glm/mat2x3.hpp \
    ../include/xd/vendor/glm/mat2x4.hpp \
    ../include/xd/vendor/glm/mat3x2.hpp \
    ../include/xd/vendor/glm/mat3x3.hpp \
    ../include/xd/vendor/glm/mat3x4.hpp \
    ../include/xd/vendor/glm/mat4x2.hpp \
    ../include/xd/vendor/glm/mat4x3.hpp \
    ../include/xd/vendor/glm/mat4x4.hpp \
    ../include/xd/vendor/glm/matrix.hpp \
    ../include/xd/vendor/glm/packing.hpp \
    ../include/xd/vendor/glm/trigonometric.hpp \
    ../include/xd/vendor/glm/vec2.hpp \
    ../include/xd/vendor/glm/vec3.hpp \
    ../include/xd/vendor/glm/vec4.hpp \
    ../include/xd/vendor/glm/vector_relational.hpp \
    ../include/xd/vendor/stb/stb_image.h \
    ../include/xd/vendor/utf8/checked.h \
    ../include/xd/vendor/utf8/core.h \
    ../include/xd/vendor/utf8/unchecked.h \
    ../include/xd/vendor/unicode_data.hpp \
    ../include/xd/vendor/utf8.h \
    ../include/xd/asset_manager.hpp \
    ../include/xd/asset_serializer.hpp \
    ../include/xd/audio.hpp \
    ../include/xd/config.hpp \
    ../include/xd/entity.hpp \
    ../include/xd/event_bus.hpp \
    ../include/xd/exception.hpp \
    ../include/xd/factory.hpp \
    ../include/xd/glm.hpp \
    ../include/xd/graphics.hpp \
    ../include/xd/lua.hpp \
    ../include/xd/ref_counted.hpp \
    ../include/xd/system.hpp \
    ../include/xd/types.hpp \
    ../include/base64.hpp \
    ../include/camera.hpp \
    ../include/canvas.hpp \
    ../include/canvas_renderer.hpp \
    ../include/canvas_updater.hpp \
    ../include/clock.hpp \
    ../include/collision_check_types.hpp \
    ../include/collision_record.hpp \
    ../include/command.hpp \
    ../include/command_result.hpp \
    ../include/commands.hpp \
    ../include/common.hpp \
    ../include/configurations.hpp \
    ../include/custom_shaders.hpp \
    ../include/direction.hpp \
    ../include/direction_utilities.hpp \
    ../include/editable.hpp \
    ../include/exceptions.hpp \
    ../include/game.hpp \
    ../include/image_layer.hpp \
    ../include/image_layer_renderer.hpp \
    ../include/image_layer_updater.hpp \
    ../include/layer.hpp \
    ../include/layer_renderer.hpp \
    ../include/layer_types.hpp \
    ../include/layer_updater.hpp \
    ../include/log.hpp \
    ../include/map.hpp \
    ../include/map_object.hpp \
    ../include/object_layer.hpp \
    ../include/object_layer_renderer.hpp \
    ../include/object_layer_updater.hpp \
    ../include/pathfinder.hpp \
    ../include/player_controller.hpp \
    ../include/rapidxml.hpp \
    ../include/rapidxml_print.hpp \
    ../include/save_file.hpp \
    ../include/scripting_interface.hpp \
    ../include/shake_decorator.hpp \
    ../include/sprite.hpp \
    ../include/sprite_data.hpp \
    ../include/sprite_holder.hpp \
    ../include/text_parser.hpp \
    ../include/tile_layer.hpp \
    ../include/tile_layer_renderer.hpp \
    ../include/tileset.hpp \
    ../include/utility.hpp

FORMS    += main_window.ui

DISTFILES += \
    ../include/xd/vendor/glm/CMakeLists.txt
